tree: Fix invalid unlocked_by reference panic
exercism/v2-configlet pull request #103
Opened 2017-10-24 18:07 UTC by tleen

See #102

2017-10-24 18:46 UTC, rpottsoh commented
Thanks @tleen for making the necessary changes.

2017-10-25 19:50 UTC, ferhatelmas requested changes
Seems test is missing `gofmt`. Otherwise good.

2017-10-25 20:00 UTC, nywilken approved these changes
@tleen this looks good to me. I am a little concerned that the warning may get missed, especially for tracks with a large set of exercises.

I left a question about your change. But this is otherwise good to merge, when you are ready.

2017-10-25 20:00 UTC, nywilken commented on cmd/tree.go
> +		parent, unlockExists := slugToExercise[e.UnlockedBy]
Do we need to run this type of exists check in other areas of the code where we expect to get a reference to an exercise?

2017-10-25 20:23 UTC, tleen commented on cmd/tree_example_test.go
> +}
@ferhatelmas is this the line that makes you think it did not pass through `gofmt`?

2017-10-25 20:26 UTC, tleen commented on cmd/tree_example_test.go
> +}
@ferhatelmas good eye on that, there are a few places it was wrong. Dunno why it didn't run on save as usual.

2017-10-25 20:31 UTC, tleen commented on cmd/tree.go
> +		parent, unlockExists := slugToExercise[e.UnlockedBy]
I don't believe so, not in `tree` anyway. The rest are referenced via the main slug which is the authoritative map key for an exercise. 

Unsure about other commands. I think once `lint` checks for this stuff it is ok for other commands to assume that config won't have bad slugs.

2017-10-25 20:32 UTC, tleen commented on cmd/tree.go
> +		parent, unlockExists := slugToExercise[e.UnlockedBy]
@nywilken the warning could be missed, but not sure how to make it stand out more?

2017-10-25 20:36 UTC, ferhatelmas commented on cmd/tree.go
> +				fmt.Sprintf("Exercise \"%s\" has an invalid unlocked_by slug: \"%s\"", e.Slug, e.UnlockedBy));
`s/%s/%q/` seems better for formatting.

2017-10-25 20:37 UTC, ferhatelmas commented on cmd/tree_example_test.go
> +func ExampleInvalidUnlockedBy(){
Sorry about nitpick. There should be a space after parens.

2017-10-25 20:40 UTC, tleen commented on cmd/tree_example_test.go
> +func ExampleInvalidUnlockedBy(){
No you're right, something has gone wonky with my `gofmt`. It did everything but that.

2017-10-25 20:50 UTC, tleen commented on cmd/tree.go
> +				fmt.Sprintf("Exercise \"%s\" has an invalid unlocked_by slug: \"%s\"", e.Slug, e.UnlockedBy));
:100: better. Great call.

2017-10-25 20:56 UTC, ferhatelmas commented on cmd/tree.go
> +		// the program, see #102. If an non-existant slug exists issue warning.
Also, `a non-existent slug` ? https://en.wiktionary.org/wiki/non-existant

2017-10-25 21:00 UTC, tleen commented on cmd/tree.go
> +		// the program, see #102. If an non-existant slug exists issue warning.
heh, a non-existant word.

2017-10-25 21:01 UTC, ferhatelmas commented on cmd/tree.go
> +		// the program, see #102. If an non-existent slug exists issue warning.
`a non-...` :wink:

2017-10-25 21:01 UTC, ferhatelmas approved these changes

2017-10-25 21:14 UTC, merged