Configurable example solution patern
exercism/v2-configlet pull request #13
Opened 2017-05-04 11:49 UTC by Insti

Fixes: #12 

Previously the pattern used to check if an example solution was present for a file was hardcoded to `[Ee]xample`.

Since support was added for ignored `.meta` directory it is no longer necessary for a solution filename to contain `example` to avoid being served to the student.

This patch adds support for configuring the pattern used to detect the presence of an example solution.

It is set via the optional key `solutionpattern` in the track's `config.json` file. The value is a string which is used to create a regular expression.

If the key is not present the default value of `[Ee]xample` will be used.

2017-05-04 17:16 UTC, kotp commented
I believe this fixes#12 ...

2017-05-06 06:55 UTC, kytrinyx commented
Thanks @Insti, the approach you describe is much better.

I'll take a close look at this in the next couple of days.

2017-05-06 13:07 UTC, kytrinyx requested changes
Overall this looks great. I just have the one request related to consistency in the config.json key name.

2017-05-06 13:07 UTC, kytrinyx commented on configlet/fixtures/track/config.json
> +  "solutionpattern": "[Ee]xample|\\.meta/solutions/[^/]*\\.rb",
The key should be `solution_pattern` to match the style of the rest of the config (`test_pattern`, `ignore_pattern`).

2017-05-06 14:44 UTC, Insti commented on configlet/fixtures/track/config.json
> +  "solutionpattern": "[Ee]xample|\\.meta/solutions/[^/]*\\.rb",
Good point, I will change that when I get a chance. :+1:

2017-05-07 09:12 UTC, Insti commented
Done, do you want me to rebase so the original commits use the underscore version?

2017-05-08 03:18 UTC, kytrinyx commented
> do you want me to force push so the original commits use the underscore version?

Yes, please!

2017-05-08 07:25 UTC, Insti commented
Done, should be ready to merge now.

2017-05-08 12:29 UTC, kytrinyx approved these changes

2017-05-08 12:29 UTC, merged

2017-05-08 12:54 UTC, kytrinyx commented
I've published a new release. The travis builds should pick it up automatically.

2017-05-08 17:01 UTC, Insti commented
Awesome. Thanks.

2017-05-08 17:01 UTC, Insti commented
Awesome. Thanks.

2017-05-08 19:35 UTC, Insti commented
Documented here: https://github.com/exercism/x-common/pull/778

2017-05-08 19:40 UTC, Insti commented
Confirmed working with travis via the xruby track.

2017-05-09 00:19 UTC, kytrinyx commented
:tada: