[DO NOT MERGE] Refactor the fmt command to rely on default marshaling of structs
exercism/v2-configlet pull request #134
Opened 2018-05-27 18:57 UTC by kytrinyx

🚧 🚧 🚧 Builds on top of #133 🚧 🚧 🚧 

----

Instead of using the OrderedMap which was introduced so that we could use alphabetic ordering of fields, this changes the fmt command to rely on the order that the fields are defined in the structs.

2018-05-30 14:54 UTC, kytrinyx commented
This rebases the branch onto the most recent master. It should be good to review properly now.

2018-05-31 03:20 UTC, nywilken commented
@kytrinyx thanks for rebasing. I'm looking through the changes and should have some feedback for you in the am.

2018-06-01 12:39 UTC, nywilken reviewed
Nicely done - breaking up the commit the way you did made reviewing easier. I have a few nitpicks, but nothing crazy. 

I ran the fmt command a few times and it appears to be working as expected. The messaging when given an invalid config is not useful `invalid character ...`, maybe we can add a more helpful error.

2018-06-01 12:39 UTC, nywilken commented on track/config.go
> +func (cfg *Config) Read(path string) error {
The method name `Read` seems like it should be something like `func (cfg *Config) LoadFromFile(path string) error` or maybe even `func NewConfigFromFile(path string) (Config, error)` so that it is a tad more explicit that it is replacing the contents of the existing Config. Thoughts?

2018-06-01 12:39 UTC, nywilken commented on track/maintainer_config.go
> +func (mCfg *MaintainerConfig) Read(path string) error {
See my comment on `Config.Read` in `config.go`

2018-06-01 12:39 UTC, nywilken commented on track/config_serializer.go
> +type ConfigSerializer interface {
What do you think about defining this interface in the `fmt` command? Seeing as it is only used there.

2018-06-01 12:39 UTC, nywilken commented on track/config_serializer.go
> +	ToJSON() ([]byte, error)
The ToJSON signature has a striking resemblance to the Marshaler interface `MarshalJSON ([]byte, error)`. However, I can't seem to get a working solution to recommend a change here. So I will leave it as a point of reference for something to think about in the future https://blog.gopheracademy.com/advent-2016/advanced-encoding-decoding/

2018-06-01 12:39 UTC, nywilken commented on cmd/fmt.go
> +	os.Mkdir(filepath.Join(outDir, "config"), os.ModePerm)
Should we add a clean up for this? Or a flag that we can toggle only when in test mode.

2018-06-01 20:37 UTC, kytrinyx commented on track/config.go
> +func (cfg *Config) Read(path string) error {
Agreed, that's much better.

2018-06-01 20:38 UTC, kytrinyx commented on track/config_serializer.go
> +type ConfigSerializer interface {
Yes, I like that better. Thanks!

2018-06-01 20:41 UTC, kytrinyx commented on cmd/fmt.go
> +	os.Mkdir(filepath.Join(outDir, "config"), os.ModePerm)
Maybe we can check if `outDir` is different from `inDir` and only create the directory if they're different. Or only create it if it doesn't exist.

```
$ go doc os.Mkdir
func Mkdir(name string, perm FileMode) error
    Mkdir creates a new directory with the specified name and permission bits
    (before umask). If there is an error, it will be of type *PathError.
```

My assumption was that Mkdir will not do anything if the directory exists, but the documentation doesn't specify. I need to check if it changes permissions in the case where it does exist.

2018-06-01 20:41 UTC, kytrinyx commented
@nywilken thanks so much for the feedback! I'll clean these things up and ping you for a final look.

2018-06-02 20:05 UTC, kytrinyx commented
Ok, I think I've addressed the feedback. Would you mind taking another look @nywilken?

2018-06-03 13:02 UTC, nywilken requested changes
@kytrinyx this is just about ready to go. I was doing a full round of testing on the changes and found a bug in the runFmt function. The function returns on the first error, but it does not display any file changes that may have happened before the error occurred. I left the reproduction steps, a recommendation, and a quick patch (feel free to change as you see fit) in my comments.

2018-06-03 13:02 UTC, nywilken commented on cmd/fmt.go
> +		os.Mkdir(filepath.Join(outDir, "config"), os.ModePerm)
:+1:

2018-06-03 13:02 UTC, nywilken commented on cmd/fmt.go
>  			return err
I recommend using multierror pkg we are using for the Generate command here. I found a bug when running  the `fmt` command on a track that is missing `maintainers.json`. Seems like we should lint for it, but that's another issue. 

If you take any track that has an improperly formatted config and remove it maintainers config running `configlet fmt <path/to/track>` will exit with an error stating that the maintainers.json was not found, which would imply that the command failed. But if you run a `git status` it will show that the config.json was actually formatted. 

I recommend that we display errors encountered along with any changes made. Something like the following:
```
> configlet fmt .                         
-> changes made to:
 config.json

-> 1 error occurred:
* open config/maintainers.json: no such file or directory
```
Sample Patch
```
diff --git a/cmd/fmt.go b/cmd/fmt.go
index 1ddea74..0dda129 100644
--- a/cmd/fmt.go
+++ b/cmd/fmt.go
@@ -8,6 +8,7 @@ import (
 
 	"github.com/exercism/configlet/track"
 	"github.com/exercism/configlet/ui"
+	"github.com/hashicorp/go-multierror"
 	"github.com/pmezard/go-difflib/difflib"
 	"github.com/spf13/cobra"
 )
@@ -61,10 +62,12 @@ func runFmt(inDir, outDir string, verbose bool) error {
 
 	var changes string
 
+	errs := &multierror.Error{}
 	for _, f := range fs {
 		diff, err := formatFile(f.cfg, f.inPath, f.outPath)
 		if err != nil {
-			return err
+			errs = multierror.Append(errs, err)
+			continue
 		}
 		if diff != "" {
 			if verbose {
@@ -76,6 +79,9 @@ func runFmt(inDir, outDir string, verbose bool) error {
 	if changes != "" {
 		ui.Print("changes made to:\n", changes)
 	}
+	if err := errs.ErrorOrNil(); err != nil {
+		return err
+	}
 	return nil
 }

```

2018-06-03 15:26 UTC, kytrinyx commented
> I was doing a full round of testing on the changes and found a bug in the runFmt function.

Thank you so much for catching this!

2018-06-03 15:52 UTC, kytrinyx commented
@nywilken I made those changes and tested them with the reproduction steps that you had 🌸

2018-06-03 18:28 UTC, nywilken approved these changes
@kytrinyx 💥 this is good to ship. I left a comment on the naming of the NewConfigFromFile method, but now I’m just nitpicking lol. I’m currently mobile reviewing so could you squash and merge, please. Otherwise I can handle it later when behind a machine.

2018-06-03 18:28 UTC, nywilken commented on track/config.go
> +func (cfg *Config) NewConfigFromFile(path string) error {
Reading it over one more time, maybe the name should be `LoadFromFile` ☮️ ☮️

2018-06-03 20:34 UTC, kytrinyx commented on track/config.go
> +func (cfg *Config) NewConfigFromFile(path string) error {
Heh. I'm ok with either. Let me think about this for an hour or so to see if I lean more strongly in either direction :)

2018-06-03 21:05 UTC, kytrinyx commented on track/config.go
> +func (cfg *Config) NewConfigFromFile(path string) error {
Ok, I decided I like LoadFromFile better :)

2018-06-03 21:06 UTC, kytrinyx commented
I will merge and cut a release tonight 🎉 Thanks for your help!

2018-06-03 21:12 UTC, merged

2018-06-05 01:14 UTC, nywilken commented on track/config.go
> +func (cfg *Config) NewConfigFromFile(path string) error {
😃 👍