implement the --diff flag for the fmt command
exercism/v2-configlet pull request #150
Opened 2018-10-20 19:07 UTC by danielj-jordan

#148 

I am a bit new to Go and eager for any comments.  Thanks

2018-10-25 02:34 UTC, nywilken submitted a review, later dismissed
@danielj-jordan I took a quick pass-through and left a few comments pertaining to the `runFmt` function signature. I will continue looking through the PR and make suggestions where possible.

Thanks again for opening up the PR!

2018-10-25 02:34 UTC, nywilken commented on cmd/fmt.go
> +	var diffFound = false
When assigning the zero value (default value) for a type it is preferred to just use `var diffFound bool`

2018-10-25 02:34 UTC, nywilken commented on cmd/fmt.go
> +		if diffFound, err := runFmt(args[0], args[0], fmtVerbose, fmtDiff); err != nil {
Seeing as `fmtVerbose` and `fmtDiff` are package level variables we should be able to access them from within `runFmt` without having to pass them in. So if you can remove the parameters from here and within the `runFmt` function you would need to update the references  of `verbose` and `diffonly` to `fmtVerbose` and `fmtDiff`

2018-10-25 02:34 UTC, nywilken commented on cmd/fmt_example_test.go
> +	runFmt("../fixtures/format/unformatted/", unformattedDir, true, false)
If you make the update so that `runFmt` uses `fmtVerbose` and `fmtDiff` directly you could remove the parameters and instead use the convention on lines 12-19 to set and reset the values for the pkg level variables `fmtVerbose` and `fmtDiff`. 

```
oldVerbose = fmtVerbose
fmtVerbose = true
defer func() {
  fmtVerbose = oldVerbose
}
```

2018-10-25 02:34 UTC, nywilken commented on cmd/fmt_test.go
> +	runFmt("../fixtures/format/formatted/", formattedDir, false, false)
Same comment I left for fmt_example_test applies here.

2018-10-30 03:24 UTC, danielj-jordan commented on cmd/fmt_test.go
> +	runFmt("../fixtures/format/formatted/", formattedDir, false, false)
Thanks @nywilken.  I made the changes that you suggested.   If you like the current code, I can squash and re-submit the PR if you like.

2018-11-02 14:23 UTC, kytrinyx requested changes
This is looking great! I have a couple of tiny comments/suggestions, but I think this is basically good to go.

2018-11-02 14:23 UTC, kytrinyx commented on cmd/fmt.go
> +		if fmtDiff == false {
Here we basically have an "if not else".

I think it would make sense to swap it around so that it reads `if fmtDiff, otherwise..."

2018-11-02 14:23 UTC, kytrinyx commented on cmd/fmt.go
> +	if diff != "" && fmtDiff == false {
It would be more idiomatic to make this `!fmtDiff`

2018-11-02 14:23 UTC, kytrinyx commented on cmd/fmt.go
> +	fmtCmd.Flags().BoolVarP(&fmtDiff, "diff", "d", false, "display the diff of the proposed changes, but do not make them.")
How would you feel about `dry-run` as the flag name instead of `diff`?
That's a very common flag name for something that would try something out, report what would happen, but then not actually make the changes.

@nywilken I'd love to hear your thoughts on this one as well.

2018-11-02 14:23 UTC, kytrinyx commented on cmd/fmt_example_test.go
> +	runFmt("../fixtures/format/unformatted/", unformattedDir)
I really like how much more readable this became now that the booleans are being assigned to the package variables!

2018-11-03 00:32 UTC, danielj-jordan commented on cmd/fmt.go
> +	fmtCmd.Flags().BoolVarP(&fmtDiff, "diff", "d", false, "display the diff of the proposed changes, but do not make them.")
I think it is better named dry-run also.

2018-11-03 01:30 UTC, danielj-jordan commented
@nywilken @kytrinyx Thanks for the feedback.  I have incorporated all your recommendations and squashed the commit.

2018-11-04 01:27 UTC, nywilken commented on cmd/fmt.go
> +	fmtCmd.Flags().BoolVarP(&fmtDiff, "diff", "d", false, "display the diff of the proposed changes, but do not make them.")
> How would you feel about `dry-run` as the flag name instead of diff?

:+1: I like that option over `diff`. I would even go so far as saying that we copy the option and messaging from the grep command 
 ```
-n, --dry-run       perform a trial run with no changes made
```

2018-11-04 01:37 UTC, nywilken commented on cmd/fmt.go
> +	fmtCmd.Flags().BoolVarP(&fmtDiff, "diff", "d", false, "display the diff of the proposed changes, but do not make them.")
Actually, looking at the original issue we want a non-zero code if there are formatting issues so a `dry-run` might not be the option we want. In fact, I wouldn't expect `dry-run` to result in a non-zero error code if the command successfully prints out the changes that would be written to the source file. 

What if we keep the `dry-run` option, but also add a `-t, --test` flag that returns a non-zero if there are formatting issue?

2018-11-04 10:39 UTC, nywilken commented on cmd/fmt.go
> +	fmtCmd.Flags().BoolVarP(&fmtDiff, "diff", "d", false, "display the diff of the proposed changes, but do not make them.")
>  What if we keep the `dry-run` option, but also add a `-t, --test` flag that returns a non-zero if there are formatting issue. 

I pulled down the branch and see that dry-run does not actually print the changes unless the verbose flag is passed as well so I would like to change my previous suggestion slightly. Which of course is open for discussion. 

Let's rename the `dry-run` option to `test` or `check` using the messaging above, enable verbosity any time the check flag is passed so that if the check fails users will see the diff. Thoughts?

2018-11-04 11:08 UTC, nywilken reviewed
@danielj-jordan @kytrinyx this is coming along nicely. I left a couple of suggestions along with my thoughts on the flag name. FWIW the code suggestions within this review should not have to change if we decide to rename the flag - only the references to the flag variable.

2018-11-04 11:08 UTC, nywilken commented on cmd/fmt.go
>  	if changes != "" {
The declaration of `diffFound` can actually be moved right above this line with a slight change

```suggestion
diffFound := changes != ""
if diffFound {
...
```

2018-11-04 11:08 UTC, nywilken commented on cmd/fmt.go
> +	var diffFound bool
This declaration can be made closer to where it is being used.

2018-11-04 11:08 UTC, nywilken commented on cmd/fmt.go
> +			diffFound = true
If you apply the suggestions made below you can drop this line.

2018-11-04 11:08 UTC, nywilken commented on cmd/fmt.go
> +		if fmtDryRun {
Seeing as the flag description specifies that no changes will be made I would drop this if/else and instead only print when changes were made. 

```
if diffFound && !fmtDryRun {
    ui.Print("changes made to:\n", changes)
}
```

2018-11-04 11:08 UTC, nywilken commented on cmd/fmt.go
> +		return diffFound, err
If you apply the suggestion on line 92 you can just return `false` with the error

2018-11-04 11:08 UTC, nywilken commented on cmd/fmt.go
> +
What do you think enabling verbosity anytime the format check is run? Something like the following right before we call `runFmt(...)` 

```
if fmtDryRun {
    fmtVerbose = true
}

```

2018-11-05 20:22 UTC, kytrinyx commented on cmd/fmt.go
> +	fmtCmd.Flags().BoolVarP(&fmtDiff, "diff", "d", false, "display the diff of the proposed changes, but do not make them.")
@nywilken these are good observations. I think that it's important that we can exit with an error code in order to be able to use this in CI. In that sense, I think that `test` communicates this better than `dry-run`.

For the doctor command, I think we _always_ need to print in the test version, whether or not `verbose` is passed. I think it's fine to not print verbose output if just running doctor to fix something.

2018-11-05 20:37 UTC, danielj-jordan commented on cmd/fmt.go
> +
Yes.  It makes sense to do this

2018-11-05 20:46 UTC, danielj-jordan commented
I want to confirm that the flag should be named —test not —dry-run.   Please reply and confirm.   Thank you

2018-11-05 20:52 UTC, kytrinyx commented
@danielj-jordan thank you for confirming. Yes! We're going with `--test` rather than `--dry-run`.

Also, the command should

1. set verbose to true even if verbose wasn't passed, and
2. exit with a non-zero code if something needs changing

2018-11-11 22:27 UTC, danielj-jordan commented
@kytrinyx @nywilken I am not sure if you got notified, but the —test flag is implemented.   It always runs with verbose.

2018-11-12 05:43 UTC, kytrinyx commented
@danielj-jordan Ah, nope! I didn't see the notification. Thanks so much, I'll take a look at this in the morning.

2018-11-13 14:07 UTC, kytrinyx requested changes
There's one more minor tweak to do (the `diffFound` thing that @nywilken mentioned previously. After that I think this is good to go!

2018-11-13 14:07 UTC, kytrinyx commented on cmd/fmt.go
> +	var diffFound bool
This should still be moved closer to where it's used 👍

2018-11-13 15:00 UTC, danielj-jordan commented
@kytrinyx  I moved the declaration closer.  Thanks

2018-11-15 14:24 UTC, kytrinyx approved these changes
This is great, thanks so much @danielj-jordan!

2018-11-15 14:28 UTC, merged

2020-10-16 16:40 UTC, ekingery commented
Closes #148