Visualization
exercism/v2-configlet pull request #83
Opened 2017-09-30 00:23 UTC by tleen

This will add a visualization command for a tree based output of a configuration file (#33). Initially prototyped in [exercism-config-tree](https://github.com/tleen/exercism-config-tree) but properly belonging to configlet.

This is my first shot at a Cobra based command line app so feedback would be greatly appreciated!

2017-10-01 16:45 UTC, kytrinyx requested changes
This looks great! I have a few minor comments, but the overall direction and implementation look super solid. 🌻 🌻 🌻

2017-10-01 16:45 UTC, kytrinyx commented on cmd/visualize.go
> +var visCmd = &cobra.Command{
I would typically name the prefix the same as the file, so `visualizeCmd`

2017-10-01 16:45 UTC, kytrinyx commented on cmd/visualize.go
> +// the exercises it unlocks.
_Unlocks_ is a bit ambiguous, since it looks like it's a verb, but it's being used as a noun. How about something like "dependentExercise" or "childExercise" or something like that?

2017-10-01 16:45 UTC, kytrinyx commented on cmd/visualize.go
> +	Unlocks []string // slugs of unlocked exercises
I would probably use `SomethingSlugs` here, where `Something` is whatever you end up naming the type... `ChildSlugs` or `DependentSlugs` or some better name that I've not thought of.

2017-10-01 16:45 UTC, kytrinyx commented on cmd/visualize.go
> +func (e exerciseUnlocks) getDescription() string {
I'm wary of names that start with `get`. I like to name functions that return a value after _what they are_ not _what they do_. Could this be just `description()`?

2017-10-01 16:45 UTC, kytrinyx commented on cmd/visualize.go
> +	// Now go into the children unlocks and do this all over again.
I'm liking "children" as a name, since you naturally use this when talking about it in comments.

2017-10-01 16:45 UTC, kytrinyx commented on cmd/visualize.go
> +	// exercises is a list of all non-deprecated exercises, in config order.
✂️ the initial empty line, I think, since none of the other functions start with an empty line.

2017-10-01 16:45 UTC, kytrinyx commented on cmd/visualize.go
> +		// Completely ignore deprecated exercises. They are dead to us.
😄 yes, they are dead to us

2017-10-01 16:45 UTC, kytrinyx commented on cmd/visualize.go
> +		// Container for this exercise
This is getting super nitpick-y, but I like to have complete sentences for comments, so I would say _Create a container for this exercise._ (including punctuation).

2017-10-01 16:45 UTC, kytrinyx commented on cmd/visualize.go
> +		// Add to slug based global lookup table
(nitpick: punctuation)

2017-10-01 16:45 UTC, kytrinyx commented on cmd/visualize.go
> +	// This is more of a warning than an error. No stdwarn :(
It sounds like it should still go to STDERR. My personal guideline for STDOUT vs STDERR is, if I'm piping the output to a file, would I want it to be included by default?

2017-10-01 17:35 UTC, tleen commented on cmd/visualize.go
> +// the exercises it unlocks.
Yeah I was a little uncomfortable with the name. I'll go whole hog into the Parent/Child terminology, it makes sense in this context.

2017-10-01 17:52 UTC, tleen commented on cmd/visualize.go
> +	// This is more of a warning than an error. No stdwarn :(
Right. I'm sending all the warnings to stderr via `ui.PrintError` to keep the output file clean.

2017-10-01 17:57 UTC, tleen commented
Thanks @kytrinyx these were good suggestions!

2017-10-01 18:37 UTC, kytrinyx commented on cmd/visualize.go
> +// the exercises it unlocks.
That sounds good.

2017-10-01 18:40 UTC, kytrinyx approved these changes
This looks great. I like how this ended up with the new names. I have one last suggested blank line deletion (sorry!), but after that this is good to be merged.

2017-10-01 18:40 UTC, kytrinyx commented on cmd/visualize.go
> +
✂️ let's ditch the blank line on this one as well.

2017-10-02 21:13 UTC, robphoenix reviewed
This is excellent @tleen, so happy to see this PR from you! :heart: 

I have a few comments and questions.

I wonder if it would be better to give the path to the track as the arg to the command, rather than specifying the `config.json` file. We can add on the filename, and it's less work for the user, not having to specify something that is a given, we know the `config.json` file holds the info, we just need to know where it is. It also means the command is less specific if the track structure changes and we need to reference more files or something.

I love the word `visualize`, but I'm concerned it's too wieldy for a command name. It's quite long and being British I tend to spell it `visualise` (https://ell.stackexchange.com/questions/5741/visualization-or-visualisation). I worry that it's appropriateness may be outweighed by it getting a little annoying to type. Alternatives could be `view`, `tree`, `show`, `list`.

The implementation though is top notch :100:

2017-10-02 21:13 UTC, robphoenix commented on cmd/visualize.go
> +// treeSpacing and treeBranching will be user over and over again
s/user/used

2017-10-02 21:13 UTC, robphoenix commented on cmd/visualize.go
> +
delete this blank line maybe? As the comment refers to both vars? Not sure about this really, no biggie.

2017-10-02 21:13 UTC, robphoenix commented on cmd/visualize.go
> +// should display exercise difficulty after slug, by default we do not.
minor rewording

```
// showDifficulty holds the --difficulty flag value to indicate whether we
// should display the exercise difficulty after slug, by default we do not.
```

2017-10-02 21:13 UTC, robphoenix commented on cmd/visualize.go
> +	Run:     runVisualizer,
To keep in sync with the rest of the commands, and the use of the word `visualize` int his command, I'd rename this `runVisualize`

2017-10-02 21:13 UTC, robphoenix commented on cmd/visualize.go
> +// exerciseParent is an extension of the exercise metatata type with with
duplicate `with`

2017-10-02 21:13 UTC, robphoenix commented on cmd/visualize.go
> +func writelns(ss []string) {
you could change this to a variadic function and get rid of `writeln`

```
func writelns(ss ...string)
```

you then wouldn't need to wrap multiple strings in a slice

```
writelns("", "core", "----")
```

2017-10-02 21:13 UTC, robphoenix commented on cmd/visualize.go
> +func printConfigurationWarning(s string) {
should this go in the `ui` package?

2017-10-02 21:13 UTC, robphoenix commented on cmd/visualize.go
> +	// Print a header: the language name with markdown style h1 underlining.
I wonder if we need the header? The user should be aware of which track they are visualizing, no? No biggie.

2017-10-02 23:20 UTC, tleen commented
> I wonder if it would be better to give the path to the track as the arg to the command, rather than specifying the config.json file. 

I thought about this some before building it to the filename. I looked at the lint command and did see that it uses a path-to-track. But then I thought that lint's concern was to lint the entire track so that made sense. The concern here is to visualize the config.json file, and really the track could have nothing to do with it. I've downloaded configfiles directly just to visualize them without having the whole track. Even though configlet does concern itself with tracks, I though that level of consistency with other command may take away some of the flexibility in visualizing configurations. Its kind of a toss up. it could really go either way, I don't feel strongly about using the path-to-file.

2017-10-02 23:23 UTC, tleen commented
> I love the word visualize, but I'm concerned it's too wieldy for a command name. I

Yes it may be. Just typing out visualize started to annoy the Unix in me. It would be a good change to shorten and get rid of a alternatively spelled word. Leaning towards `tree` since this is a track version of the unix `tree` command. I'll make this change if nobody thinks it would get confusing or has a better name!

2017-10-02 23:24 UTC, tleen commented on cmd/visualize.go
> +func writelns(ss []string) {
This is such a better idea!

2017-10-02 23:29 UTC, tleen commented on cmd/visualize.go
> +func printConfigurationWarning(s string) {
What do you think? I would probably still need this wrapper here because I use configuration warning boilerplate. Really I wanted to wrap up something that was like PrintError but was for PrintWarning, but since it would still be writing to Error it seemed more appropriate to keep it local. But I wanted it to be clear in the code that it was *not* an error. 

Do you think there is a place in ui for a boilerplated warning about configuration like this?

2017-10-02 23:38 UTC, tleen commented on cmd/visualize.go
> +	// Print a header: the language name with markdown style h1 underlining.
The user should know since they need to give the path to it. The header is more of a convenience for the user since I see this being outputted to a file often then pasted into comments in track configuration discussions. I almost want to put some sort of commit hash stamp in there too! 

Without making things too complicated it make make sense (if not here, soon) to add a more markdown compatible mode for copying and pasting into comments. We would have to wrap the actual tree in a `text` code block which would not look great on the command line. Perhaps --md or something? That would add the adornments.

2017-10-02 23:47 UTC, tleen commented on cmd/visualize.go
> +	Run:     runVisualizer,
I'll fold this one into the command rename.

2017-10-02 23:52 UTC, tleen commented on cmd/visualize.go
> +func writelns(ss []string) {
It should probably be called writeLines too.

2017-10-03 10:38 UTC, robphoenix commented on cmd/visualize.go
> +func printConfigurationWarning(s string) {
I think it's doing a similar thing to `ui.Print` and `ui.PrintError`, wrapping a message to the user in a consistent manner.

> I would probably still need this wrapper here because I use configuration warning boilerplate. 

I'm not sure I follow. Do you need this code in the `cmd` package? Is `configurationWarning` only used by `printConfigurationWarning`? It could be inside the function, rather than a global.

This could go in the `ui` package as a `ui.PrintConfigWarning`. It feels like an appropriate separation of concerns. I think that would still keep it clear in the code that it's not an error. I could be wrong though. :smiley:

2017-10-03 10:40 UTC, robphoenix commented on cmd/visualize.go
> +	// Print a header: the language name with markdown style h1 underlining.
>  I see this being outputted to a file often then pasted into comments in track configuration discussions

Totally valid point, yes you're right. :+1: 

> Without making things too complicated it make make sense (if not here, soon) to add a more markdown compatible mode for copying and pasting into comments. We would have to wrap the actual tree in a text code block which would not look great on the command line. Perhaps --md or something? That would add the adornments.

Yes, I think this is certainly a possibility.

2017-10-03 10:44 UTC, robphoenix commented
> The concern here is to visualize the config.json file, and really the track could have nothing to do with it. I've downloaded configfiles directly just to visualize them without having the whole track. 

This is a really good point. If we wanted I suppose we could even allow both by including a check on the arg, if it's a directory append the filename? This would take away the either/or choice and let the command do the work rather than the user.

2017-10-03 10:46 UTC, robphoenix commented
> Leaning towards tree since this is a track version of the unix tree command. I'll make this change if nobody thinks it would get confusing or has a better name!

:+1:

2017-10-03 11:14 UTC, tleen commented on cmd/visualize.go
> +func printConfigurationWarning(s string) {
Yeah I could hardcode the `configurationWarning` var into the `printConfigurationWarning`. It seemed like one of those things that you would put on top of a file as a easy to find setting for the code. That may be me coding Go like another language instead of doing things idomatically. I could move the whole thing over to ui if we think other commands could find it useful. In the tree implementation it is very much centered around nextercism which is why the configuration warning boilerplate is about nextercism. That would probably be appropriate for all warnings.

@nywilken what do you think? Could you see a use for a `ui.PrintConfigurationWarning`? or a `u.PrintWarning`? If we had that we could then have a global flag to enable/disable warnings...

(This may be more change than we should do in the context of this command being added?)

2017-10-03 11:17 UTC, robphoenix commented on cmd/visualize.go
> +func printConfigurationWarning(s string) {
>  I could move the whole thing over to ui if we think other commands could find it useful.

In my mind it's not necessarily about making it accessible to other commands, it's more that it's functionality is inline with the `ui` methods.

> This may be more change than we should do in the context of this command being added?

Yes. I think for now it may be best to leave it as is and we can move it in a separate PR.

2017-10-03 11:22 UTC, tleen commented
> This would take away the either/or choice and let the command do the work rather than the user.

Yeah that is a good compromise between doing it like the other commands but allowing a separate file to be used as well:

```sh
$ GET https://raw.githubusercontent.com/exercism/lua/master/config.json > lua-nextercism-config.json
$ configlet tree lua-nextercism-config.json
```

2017-10-03 11:25 UTC, tleen commented on cmd/visualize.go
> +func printConfigurationWarning(s string) {
Ok, it could involve some discussion. Once we get this in we can open up an issue about moving warnings or nextercism specific warnings into ui. :+1:

2017-10-03 13:51 UTC, nywilken commented
@tleen I'm a little late to the party, but great work. This is a solid PR. 

I have some thoughts on the command name and output. Which I will leave inline. I'm mobile reviewing so please bare with me as my comments trickle in.

2017-10-03 14:27 UTC, tleen commented
@nywilken I appreciate any input on the PR. Thanks!

2017-10-03 15:42 UTC, kytrinyx commented
I like `tree` - short, sweet, familiar without being confusing due to punniness.

2017-10-03 16:50 UTC, nywilken commented
Regarding the command name, I actually think `list` gives us more flexibility for expansion and reads a little better the `tree` when read as `configlet list lua-config.json` vs `configlet tree lua-Config.json`

What do I mean by flexibility?
Well tree is a well known command that prints a hierarchy . But with a list command we could easy list all the exercises implemented by the track (flat view), and provide a `--tree` flag to get a tree format. Adding in other flags. I guess we could add a flatten to the tree command. 

The latter brings me to the output. I believe in the "Rule of Composition"; more specifically, I think we should be able to pipe the output in another program without having modification.

2017-10-03 17:38 UTC, tleen commented
@nywilken For the piping, do you think the headers and stuff in the output is keeping the output from being well-pipeable or is the nature of the tree shape itself?

You envision the listing as a new line separated listing of exercise slugs, and `--tree` outputs as tree format?

2017-10-03 18:57 UTC, kytrinyx commented
> Regarding the command name, I actually think list gives us more flexibility

Yepp. That would let us add a --mode or --format flag or something to switch on which sort of list we want.

2017-10-03 23:32 UTC, tleen commented
So the consensus would be `list`, with the default output being a listing of all exercises, and a `--format` arg that would have `default` for the normal list and `tree` for the tree list?

2017-10-04 01:27 UTC, nywilken commented
> @nywilken For the piping, do you think the headers and stuff in the output is keeping the output from being well-pipeable or is the nature of the tree shape itself?

Nature of the tree shape. 

> Do you envision the listing as a new line separated listing of exercise slugs, and --tree outputs as tree format?

Yes, that's what I'm thinking

2017-10-04 12:54 UTC, robphoenix commented
I wonder if this is perhaps trying to pack too much into one command. Is there any reason we couldn't have both `list` and `tree`?

2017-10-04 13:23 UTC, tleen commented
It can be a tricky thing, designing command line apps with subcommands. You can look at it from the code perspective which would be "is there enough redundancy that I can fit this into one conceptual code unit with minimal additional code?" (Which in this case I think so.) But this is probably the wrong pattern of thought and we should look at what a user would expect. In this case it would be the user asking "how can I visualize my configuration file without having to get into the JSON?" When you look at it from this user perspective it may make more sense to have a single subcommand with the sole job of answering that question. Output formats just being a matter of immediate need.

I could see the usefulness of the `list` command as a generic place to put the visualizations. Even if for this pull we stick with only one (tree) or two (tree and newline-separated). I sort of took both approaches to visualizations in thinking this problem out through code: [single-purpose](https://github.com/tleen/exercism-config-tree) and [multiple-purpose](https://github.com/tleen/exercism-config-visualizations)!

If we go the single subcommand, multiple output formats route, would it make sense to not use `list` as the command name and use that as an output format? Perhaps the subcommand could be something as  simple as `output`:
```
configlet output . --fmt=list --with-difficulty
```

(I appreciate the opportunity to think out loud :mega: on this with you all. It is very helpful!)

2017-10-06 05:24 UTC, kytrinyx commented
> configlet output . --fmt=list --with-difficulty

I find this one difficult to mentally keep track of. Output _what_ exactly? And I think of `fmt` as re-formatting, and we already have a `fmt` command. So I worry that it will be like with the `tar` command where I can never remember which letters I need to use and the order of arguments.

So far I prefer tree, with the additional `--with-difficulty` flag. It's super explicit, and it's really about listing out the dependencies visually.

I'm also fine with `configlet list --tree [--with-difficulty]`, though I'm not certain that we actually need it.

2017-10-06 11:34 UTC, tleen commented
Ok, I think I'll go with `configlet list --tree [--with-difficulty]` and see how the maintainers like it.

2017-10-06 14:33 UTC, kytrinyx commented
> If we see some demand for list we can talk about moving it in with tree or separating.

That sounds like a plan!

2017-10-07 15:55 UTC, tleen commented
I think this may have everything we need to add?

2017-10-07 16:48 UTC, kytrinyx approved these changes
🚢 This looks great!

2017-10-07 16:49 UTC, kytrinyx commented
@tleen Not to deliberately make more work for you, but would you be interested in being a co-maintainer on this repo?

2017-10-07 22:00 UTC, robphoenix commented
> @tleen Not to deliberately make more work for you, but would you be interested in being a co-maintainer on this repo?

I wholeheartedly endorse this. :heart:

2017-10-07 22:21 UTC, tleen commented
Sure, it would be my pleasure. I'm always looking for places to squeeze in more Go!

2017-10-07 23:26 UTC, kytrinyx commented
Yay. Done! And thank you ❤️

2017-10-08 14:52 UTC, merged

2017-10-08 15:06 UTC, nywilken commented
@tleen welcome!!!! I'm looking forward to working on more PRs with you.

2017-10-08 15:27 UTC, tleen commented
Same @nywilken glad to be able to help!

2017-10-09 16:11 UTC, robphoenix commented
@tleen woop woop! :tada: welcome :handshake: