Remove coupling between description and metadata
exercism/v2-configlet pull request #84
Opened 2017-10-01 13:43 UTC by nywilken

Currently, the loading of a custom exercise readme description (i.e `$exercise_path/.meta/description.md`)  requires that a copy of the `metadata.yml` file exist within `$exercise_path/.meta` . This change removes that coupling so that maintainers can override descriptions without the need of a duplicated `.metadata.yml` file. 

closes #65

2017-10-01 16:14 UTC, kytrinyx requested changes
The granular overrides look good—it looks like we basically have the same behavior as before, but on a file-by-file basis rather than making the assumption that we will load all the metadata from the same location.

I discovered when reading this that I have strong opinions about fixtures. Who knew? :-)

Fixtures are a huge source of pain over time, so getting them right as early as possible is an enormous win.

If it's not clear what I mean with my comments about fixtures, please discuss so we can hash it all out (and maybe we can document this afterwards; it feels important).

2017-10-01 16:14 UTC, kytrinyx commented on fixtures/elements/config.json
> +      "uuid": "zzz",
For fixtures I have the following general guideline:

* They should be nested within a directory that isolates them to a specific testing context.
* They should not be reused in different contexts
* The fixtures should be minimal, including only the features necessary to prove the point

If you look at the fixture tree, we're mostly following these principles. See "alternate", "format", "deprecated" (with different deprecations nested within them), and "broken-maintainers".


```
fixtures/
├── alternate
│   └── problem-specifications
│       └── exercises
│           └── one
│               ├── description.md
│               └── metadata.yml
├── broken-maintainers
│   ├── config
│   │   └── maintainers.json
│   └── config.json
├── broken.json
├── deprecated
│   ├── hints-both
│   │   ├── config.json
│   │   └── exercises
│   │       └── fake
│   │           └── HINTS.md
│   ├── hints-old
│   │   ├── config.json
│   │   └── exercises
│   │       └── fake
│   │           └── HINTS.md
│   ├── inserts-both
│   │   ├── config
│   │   │   └── exercise-readme-insert.md
│   │   ├── config.json
│   │   ├── docs
│   │   │   └── EXERCISE_README_INSERT.md
│   │   └── exercises
│   │       └── fake
│   └── inserts-old
│       ├── config.json
│       ├── docs
│       │   └── EXERCISE_README_INSERT.md
│       └── exercises
│           └── fake
├── elements
│   ├── config
│   │   └── maintainers.json
│   ├── config.json
│   └── exercises
│       └── aluminum
│           ├── example.ext
│           └── test.ext
├── empty.json
├── fake-exercise
│   ├── example.ext
│   ├── fake_test.ext
│   ├── specs
│   │   └── file.ext
│   └── subdir
│       └── solution.ext
├── format
│   ├── formatted
│   │   ├── config.json
│   │   └── maintainers.json
│   ├── malformed
│   │   ├── config.json
│   │   └── maintainers.json
│   ├── minimised
│   │   ├── config.json
│   │   └── maintainers.json
│   └── unformatted
│       └── config.json
├── numbers
│   ├── config
│   │   ├── exercise-readme-insert.md
│   │   ├── exercise_readme.go.tmpl
│   │   └── maintainers.json
│   ├── config.json
│   └── exercises
│       ├── one
│       │   ├── example.ext
│       │   └── test.ext
│       ├── three
│       │   └── tests
│       │       └── three.ext
│       ├── two
│       └── zero
└── problem-specifications
    └── exercises
        ├── fake
        │   ├── description.md
        │   └── metadata.yml
        ├── one
        │   ├── description.md
        │   └── metadata.yml
        └── two
            ├── description.md
            └── metadata.yml
```

I don't recall what I was thinking with "numbers" and "problem-specifications" nested at the top level. Probably that they were "happy path" situations. I'm not sure that's a good idea anymore, since I clearly can't remember 3 months later :(

For the functionality in this PR, we should have a nested fixture directory that is called something specific to the functionality, like `granular-metadata-overrides` and have whatever fixtures we need to fully specify the behavior within that directory.

2017-10-01 16:14 UTC, kytrinyx commented on track/problem_specification_test.go
> +	saved := ProblemSpecificationsPath
What does `saved` mean?

2017-10-02 21:35 UTC, robphoenix commented on fixtures/elements/config.json
> +      "uuid": "zzz",
> I'm not sure that's a good idea anymore, since I clearly can't remember 3 months later :(

I know this feeling :smile: 

Out of interest, can I ask if this is a *Go thing*? I ask out of pure ignorance. For instance should the dir be called `testdata` instead of fixtures? (https://dave.cheney.net/2016/05/10/test-fixtures-in-go)

Would you split the directory up according to the command the fixture is being used to test? So have a sub-dir per command?

2017-10-02 21:40 UTC, robphoenix approved these changes
:+1:

2017-10-03 03:31 UTC, nywilken commented on fixtures/elements/config.json
> +      "uuid": "zzz",
> For fixtures I have the following general guideline:
     - They should be nested within a directory that isolates them to a specific testing context.
     - They should not be reused in different contexts
     - The fixtures should be minimal, including only the features necessary to prove the point

Nice, this is helpful. I'm pretty sure I spent more time thinking how to organize the tests, and whether or not to create new fixtures than I did writing the fix. 

On the topic of fixtures, do you have a convention for naming? I struggle on just how granular to go. I try to lean towards shorter names, but I get how they may not provided enough context. Is it safe to say, if the fixture name properly explains its test context the length is irrelevant?

2017-10-03 03:32 UTC, nywilken commented on fixtures/elements/config.json
> +      "uuid": "zzz",
> Out of interest, can I ask if this is a Go thing? I ask out of pure ignorance. For instance should the dir be called testdata instead of fixtures? (https://dave.cheney.net/2016/05/10/test-fixtures-in-go)

Great question, thanks for sharing the link.

2017-10-03 15:38 UTC, kytrinyx commented on fixtures/elements/config.json
> +      "uuid": "zzz",
> Out of interest, can I ask if this is a Go thing?

Nope—this is purely me reacting to years of painful fixtures. I'd be happy to rename per Go conventions.

> Would you split the directory up according to the command the fixture is being used to test? So have a sub-dir per command?

Not really, unless it makes sense that way. Or rather—not _just_ sub commands. Take the "deprecations" for example. In other codebases I've worked in, we have one broad set of fixtures that have all the features that all the tests need. So you deprecate a field somewhere, and randomly (who knows which one) one of the fixtures will have the deprecated field, a different one will have the new field, and one will have both, so you can see which overrides which. Here I have a directory named `deprecation`, with one subdirectory for each specific deprecation. These fixtures don't need to have any other features, just the fields in question. And once we're ready to kill off the deprecated behavior, we can delete a subdirectory entirely.

When introducing an "alternate path" for problem-specifications, where you can pass it with a command-line switch, I added a specific subdirectory for it.

>  I try to lean towards shorter names, but I get how they may not provided enough context. Is it safe to say, if the fixture name properly explains its test context the length is irrelevant?

With fixtures (and tests in general) I tend to lean towards verbose and explicit. With a fixture I tend to want to know: under what circumstances would this need to be updated or deleted. So if we no longer wanted to support alternate paths for problem-specifications, or if there was a bug in how we were handling it, or we needed a third way to deal with it, it would all go in the same place.

Not sure if this helps—it's all just stuff I'm making up as we go along.

2017-10-04 14:49 UTC, robphoenix commented on fixtures/elements/config.json
> +      "uuid": "zzz",
This is really helpful, thanks. I'm totally learning here, having ashamedly not implemented a lot of testing in my time :scream:, and as such don't have much to add. I like that the fixtures are grouped via behaviour than command, that makes sense. The more descriptive names make sense also.

I looked at changing `fixtures` to `testdata`, an opportunity to learn vim's [argdo](http://vimcasts.org/episodes/using-argdo-to-change-multiple-files/) :smile:, and it introduced a bug, as the exercise paths in the *fixtures/testdata* dir now contained the word `test` whether it had any tests in it or not, thus implying there were tests present and passing linting where it should fail.

2017-10-07 17:03 UTC, kytrinyx commented on fixtures/elements/config.json
> +      "uuid": "zzz",
Oh, man. I'm so often kicked in the gut by the assumptions that my tools make about what I want.

2017-10-07 17:03 UTC, kytrinyx commented on track/problem_specification_test.go
> +	saved := ProblemSpecificationsPath
Having seen a couple of other PRs go by, I realize that `saved` means `originalPath` - can we use originalSpecPath or origSpecPath here?

2017-10-07 18:24 UTC, nywilken commented on track/problem_specification_test.go
> +	saved := ProblemSpecificationsPath
You called this out in a different PR and I started moving away from saved. But I never answered you, my bad. I'll catch this one in the update 🙌🏽

2017-10-08 15:02 UTC, nywilken commented
@kytrinyx I made a few updates to reflect the comments about fixtures - the changes are pretty much, still, a work in progress. Once it's good to go I will ping the team for review.

2017-10-10 15:17 UTC, nywilken commented
@kytrinyx @robphoenix this is ready for review.

2017-10-13 17:10 UTC, nywilken commented
If there are no objections, I would like to merge this in and, possibly, start work for cutting a new release. Let me know 🙏

2017-10-13 18:26 UTC, tleen reviewed
LGTM. Good fix here thanks!

2017-10-13 21:43 UTC, robphoenix approved these changes
:+1: go for it

2017-10-13 23:59 UTC, tleen approved these changes

2017-10-14 00:23 UTC, merged

2017-10-14 00:28 UTC, nywilken commented
Thanks!