Add support for custom readme titles via the title property in metatdata.yml
exercism/v2-configlet pull request #85
Opened 2017-10-01 14:21 UTC by nywilken

closes #76

2017-10-01 16:21 UTC, kytrinyx requested changes
This looks good. I have a couple of small comments, but nothing major.

2017-10-01 16:21 UTC, kytrinyx commented on cmd/lint_test.go
> +	saved := disableHTTPChecks
What does `saved` mean? Can we name it specific to what we're saving?

2017-10-01 16:21 UTC, kytrinyx commented on track/exercise_readme_test.go
> +			description: "readme with title cased slug for .Spec.Name.",
Maybe "readme with title inferred from slug"?

2017-10-01 16:21 UTC, kytrinyx commented on track/problem_specification.go
> +func (spec *ProblemSpecification) titleCaseSlug() string {
When naming things that return a value, I try to name them based on _what they are_ rather than _what they do_.

I don't know what the best name is here. _InferredTitle_? _NamifiedSlug_? _TitleCasedSlug_?

2017-10-02 21:26 UTC, robphoenix approved these changes
LGTM :+1:

2017-10-03 03:15 UTC, nywilken commented on track/problem_specification.go
> +func (spec *ProblemSpecification) titleCaseSlug() string {
Good advice. I'll update. 

> I don't know what the best name is here. InferredTitle? NamifiedSlug? TitleCasedSlug?

I'm inclined to use `titleCasedSlug` as ProblemSpecification types should use the Name method for getting the readme title. Do you think it the method should be exported?

2017-10-03 03:21 UTC, nywilken commented on cmd/lint_test.go
> +	saved := disableHTTPChecks
I see how saved can be confusing.

2017-10-03 03:22 UTC, nywilken commented
@kytrinyx @robphoenix thanks for the first round of reviews. I'll make the suggested updated and push out.

2017-10-03 15:31 UTC, kytrinyx commented on track/problem_specification.go
> +func (spec *ProblemSpecification) titleCaseSlug() string {
I don't think it needs to be exported, since we'll be using Name (or whatever it is) to be either the explicit title or the inferred one.

2017-10-03 15:31 UTC, kytrinyx approved these changes

2017-10-06 18:17 UTC, nywilken commented
@kytrinyx @robphoenix I know I got approval on this PR already, but I did make some changes to the tests and fixtures that I would like to get your approval on before I merge. 🙇

2017-10-07 16:53 UTC, kytrinyx approved these changes
I have a tiny quibble with the fixture, but as soon as that is addressed I would say 🚢 -- this looks great! 🌷

2017-10-07 16:53 UTC, kytrinyx commented on fixtures/titled-exercises/config.json
> +      "difficulty": 4
Is the difficulty relevant to the titles? If not I would set this to 1 (since 1 seems to be the default). Or even better—if the test doesn't blow up I would delete all but the slug field.

2017-10-07 18:41 UTC, nywilken commented on fixtures/titled-exercises/config.json
> +      "difficulty": 4
Good call!

2017-10-08 13:08 UTC, merged

2017-10-20 14:54 UTC, nywilken commented
@petertseng support for custom titles is now part of [configlet](https://github.com/exercism/configlet/releases/tag/v3.6.0). Please let me us know if you run into any issues when generating new READMEs.