Add --track-id flag to lint command
exercism/v2-configlet pull request #90
Opened 2017-10-04 16:08 UTC by robphoenix

This is a tool specific solution to #80

2017-10-04 19:49 UTC, nywilken requested changes
I left a comment on the issue, pertaining to this PR. I also left a few comments, if we end up going this route. 

Thanks for pushing this fix along. Great stuff!

2017-10-04 19:49 UTC, nywilken commented on track/track.go
> +func (t *Track) RenameID(name string) {
I get the idea, but this code can live directly within lintTrack. No need for an exported function on track.

2017-10-04 19:49 UTC, nywilken commented on track/track_test.go
> +func TestTrackRenameID(t *testing.T) {
I think we can do away with this test. See my comment above about dropping the function RenameID

2017-10-04 20:55 UTC, robphoenix commented on track/track.go
> +func (t *Track) RenameID(name string) {
Ahh you're so right, I totally over complicated that. :roll_eyes: Thanks!

2017-10-06 20:52 UTC, nywilken approved these changes
@robphoenix this looks good - just one minor nit pick before we merge.

2017-10-06 20:52 UTC, nywilken commented on cmd/lint.go
> +	lintCmd.Flags().StringVar(&trackID, "track-id", "", "Specify track name.")
I think the messaging needs to be more descriptive. Specifically, it should elaborate why a user would want to specify a track name and what it defaults to. Maybe something like `Override the default track-id with 'name' (defaults to directory name)`

2017-10-07 16:58 UTC, kytrinyx commented on cmd/lint.go
> +	lintCmd.Flags().StringVar(&trackID, "track-id", "", "Specify track name.")
I'd prefer _Specify the track ID_ rather than _Specify the track name_, since name is ambiguous. The track name is the name of the language, which is different from the ID.

2017-10-07 16:59 UTC, kytrinyx commented on cmd/lint.go
> +	// trackID flag allows the user to specify the name of the track,
Ditto here for s/name/ID/

2017-10-07 16:59 UTC, kytrinyx approved these changes
Other than the bit about track name vs track ID, this looks great. Good to merge as soon as that is fixed.

2017-10-09 12:28 UTC, merged